sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

language: scala

script:
    - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

scala:
  - 2.13.0
  - 2.12.4
  - 2.11.11

# whitelist
branches:
  only:
    - master
